### PR TITLE
Automatically create data streams

### LINKED ISSUE #43: Data Stream may already exist
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

**Is your feature request related to a problem? Please describe.**

Plugin tries to create data stream when it doesn't need to, and data stream may already exist in some scenarios. 
If data stream was created between check for data stream and PUT, retry operate would loop until finishing (concurrent execution problem):
https://github.com/fluent/fluent-plugin-opensearch/blob/main/lib/fluent/plugin/out_opensearch_data_stream.rb#L113

**Describe the solution you'd like**

allow _bulk POST to automatically create data streams matching the index template

**Describe alternatives you've considered**

N/A

**Additional context**

##### Data stream doesn't exist, so it will try to create
2022-03-31 16:28:32 +0000 [info]: #0 [out_all] Specified data stream does not exist. Will be created: <[404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [my-data-stream]","index":"verrazzano-application-hello-helidon","resource.id":"my-data-stream","resource.type":"index_or_alias","index_uuid":"_na_"}],"type":"index_not_found_exception","reason":"no such index [my-data-stream]","index":"my-data-stream","resource.id":"my-data-streamn","resource.type":"index_or_alias","index_uuid":"_na_"},"status":404}>

##### Someone else had created the data stream between 16:28:32 and 16:28:34. Now we get 400 err from opensearch because the data stream is present now.
2022-03-31 16:28:34 +0000 [warn]: #0 [out_all] Could not communicate to OpenSearch, resetting connection and trying again. [400] {"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"data_stream [my-data-stream] already exists"}],"type":"resource_already_exists_exception","reason":"data_stream [my-data-stream] already exists"},"status":400}

### PR DESCRIPTION
**Pull request by anders-swanson**
@cosmo0920 Fixes #43

### CODE REVIEW

**Comment by anders-swanson** [comment]
Does this need a new test? Only change was to delete code.

**Review by cosmo0920 — APPROVED** [review]

**Comment by cosmo0920** [comment]
Hmm, OpenSearch will create DataStreams indices when they don't exist. This is curious behavior....

**Comment by anders-swanson** [comment]
See OpenSearch docs: https://opensearch.org/docs/latest/opensearch/data-streams/#step-2-create-a-data-stream
Specifically:
```
Because we have a matching index template with a data_stream object, OpenSearch automatically creates the data stream
```

**Comment by cosmo0920** [comment]
Wow, it’s user-oriented feature! Thanks for the info.

**Comment by ayaranga** [comment]
@cosmo0920 Can you please make this fix available in a release?

**Pull request merged**
